spring:
  application:
    name: user-service
  profiles:
    group:
      dev: "security,kafka,cache,jpa,mongo"
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        enabled: true
        sources:
          - namespace: spring-market
            name: common-config
          - namespace: spring-market
            name: common-config-${spring.profiles.active}
          - namespace: spring-market
            name: user-service
          - namespace: spring-market
            name: user-service-${spring.profiles.active}


