apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - command: ["/opt/keycloak/bin/kc.sh"]
          args:
             - "start-dev"
             - "--proxy-headers=xforwarded"
             - "--http-enabled=true"
             - "--http-port=8080"
             - "--hostname=auth.local"
             - "--hostname-strict=false"
             - "--hostname-backchannel-dynamic=false"
#             - "--optimized"
          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka-0.kafka-headless.messaging.svc.cluster.local:9090,kafka-1.kafka-headless.messaging.svc.cluster.local:9090,kafka-2.kafka-headless.messaging.svc.cluster.local:9090
            - name: KC_DB
              value: postgres
            - name: KC_DB_PASSWORD
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-db.database.svc.cluster.local:5400/keycloak
            - name: KC_DB_USERNAME
              value: postgres
            - name: KC_HOSTNAME_PORT
              value: "8080"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
#            - name: KEYCLOAK_ADMIN
#              value: "admin"
#            - name: KEYCLOAK_ADMIN_PASSWORD
#              value: "admin"
            - name: KC_HEALTH_ENABLED
              value: "true"
          name: keycloak
          image: ghcr.io/cryptic901/springmarket/keycloak:latest
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "700m"
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
