controller:
  replicaCount: {{ .Values.controller.replicaCount }}

  resources:
    requests:
      cpu: {{ .Values.controller.resources.requests.cpu }}
      memory: {{ .Values.controller.resources.requests.memory }}
    limits:
      cpu: {{ .Values.controller.resources.limits.cpu }}
      memory: {{ .Values.controller.resources.limits.cpu }}

  metrics:
    enabled: {{ .Values.controller.metrics.enabled }}
    serviceMonitor:
      enabled: {{ .Values.controller.metrics.serviceMonitor }}

  config:
    proxy-connect-timeout: "{{ index .Values.controller.config "proxy-connect-timeout" }}"
    proxy-read-timeout: "{{ index .Values.controller.config "proxy-read-timeout" }}"
    proxy-send-timeout: "{{ index .Values.controller.config "proxy-send-timeout" }}"

    log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id'

  service:
    type: {{ .Values.controller.service.type }}

  podLabels:
    app: {{ .Values.controller.podLabels.app }}
    environment: {{ .Values.controller.podLabels.environment }}

defaultBackend:
  enabled: {{ .Values.defaultBackend.enabled }}