server:
  port: 8888
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        native:
          search-locations: file:/config
  security:
    user:
      name: config
      password: config

management:
  tracing:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      show-details: always