server:
  port: 8888
eureka:
  instance:
    hostname: config-server
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cryptic901/SpringMarket
          clone-on-start: true
          search-paths: config
          default-label: master
  security:
    user:
      name: config
      password: config

management:
  tracing:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      show-details: always