apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-service
  name: inventory-service
  namespace: spring-market
spec:
  ports:
    - name: http
      port: 8087
      targetPort: 8087
  selector:
    app: inventory-service
  type: ClusterIP