spring:
  application:
    name: AnalyticService
  profiles:
    group:
      dev: "security,kafka,cache,feign,jpa,mongo,k8s"
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        enabled: true
        sources:
          - namespace: spring-market
            name: common-config
          - namespace: spring-market
            name: common-config-${spring.profiles.active}
          - namespace: spring-market
            name: analytic-service-config
          - namespace: spring-market
            name: analytic-service-config-${spring.profiles.active}