spring:
  application:
    name: ReviewService
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev
      username: config
      password: config
  config:
    import: "configserver:"
