eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  security:
    jwt:
      secret: G7nHsKi/JvNfskJg4m4bbq2KqQOuvPWXAzTyOq7SmQA=
      expiration: 20h
    cookie:
      name: authToken
  application:
    name: Gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: auth-routes
          uri: lb://AuthenticationService
          predicates:
            - Path=/api/v1/auth/**

        - id: product-routes
          uri: lb://ProductService
          predicates:
            - Path=/api/v1/products/**
            - Path=/api/v1/categories/**

        - id: order-routes
          uri: lb://OrderService
          predicates:
            - Path=/api/v1/orders/**

        - id: cart-routes
          uri: lb://CartService
          predicates:
            - Path=/api/v1/carts/**

        - id: review-routes
          uri: lb://ReviewService
          predicates:
            - Path=/api/v1/reviews/**

        - id: user-routes
          uri: lb://UserService
          predicates:
            - Path=/api/v1/users/**

        - id: payment-routes
          uri: lb://PaymentService
          predicates:
            - Path=/api/v1/payments/**

        - id: notification-routes
          uri: lb://NotificationService
          predicates:
            - Path=/api/v1/notifications/**

        - id: analytic-routes
          uri: lb://AnalyticService
          predicates:
            - Path=/api/v1/admin/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org:
      springframework:
        cache: TRACE
        web: TRACE
        http: TRACE
        security: TRACE
server:
  port: 7777
