networks:
  spring-market:
    driver: bridge

services:
  kafka-1:
    image: apache/kafka:latest
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - "9092:9092"
    stop_grace_period: 30s
    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9090
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    networks:
      - spring-market
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "opt/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9090 || exit 1"]
      interval: 15s
      timeout: 60s
      retries: 5
      start_period: 60s
    volumes:
      - kafka-1_data:/var/lib/kafka/data

  kafka-2:
    image: apache/kafka:latest
    container_name: kafka-2
    hostname: kafka-2
    ports:
      - "9094:9094"
    stop_grace_period: 30s
    environment:
      KAFKA_NODE_ID: 2
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9090
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    networks:
      - spring-market
    restart: always
    depends_on:
      kafka-1:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "opt/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9090 || exit 1"]
      interval: 15s
      timeout: 60s
      retries: 5
      start_period: 60s
    volumes:
      - kafka-2_data:/var/lib/kafka/data

  kafka-3:
    image: apache/kafka:latest
    container_name: kafka-3
    hostname: kafka-3
    ports:
      - "9096:9096"
    stop_grace_period: 30s
    environment:
      KAFKA_NODE_ID: 3
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9090
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    networks:
      - spring-market
    restart: always
    depends_on:
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "opt/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9090 || exit 1"]
      interval: 15s
      timeout: 60s
      retries: 5
      start_period: 60s
    volumes:
      - kafka-3_data:/var/lib/kafka/data

  debezium:
    image: debezium/connect:2.7.3.Final
    container_name: debezium
    hostname: debezium
    restart: always
    ports:
      - "3434:8083"
    environment:
      REST_PORT: 8083
      BOOTSTRAP_SERVERS: kafka-1:9090,kafka-2:9090,kafka-3:9090
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: kafka-connect-config
      OFFSET_STORAGE_TOPIC: kafka-connect-offset
      STATUS_STORAGE_TOPIC: kafka-connect-status
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    networks:
      - spring-market
    volumes:
      - debezium_data:/debezium
      - ./connectors:/docker-entrypoint-init.d/
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/connectors || exit 1"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.2-m01
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - redis_data:/data
    networks:
      - spring-market

  postgres:
    user: "0:0"
    container_name: postgres
    image: postgis/postgis:18-3.6-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: ["postgres", "-c", "wal_level=logical", "-c", "max_replication_slots=20", "-c", "max_wal_senders=20", "-c", "max_connections=200"]
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - spring-market
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-db:
    image: mongo:8.2.1
    container_name: mongo-db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - spring-market
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-db:
    image: postgres:18-alpine
    container_name: keycloak-db
    restart: always
    ports:
      - "5400:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - spring-market
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d keycloak"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: keycloak/keycloak:26.0.0
    container_name: keycloak
    entrypoint: [ "/bin/bash", "-c" ]
    command: >
      "/opt/keycloak/bin/kc.sh build
      --metrics-enabled=true &&
        /opt/keycloak/bin/kc.sh start-dev 
      --proxy-headers=xforwarded 
      --http-enabled=true 
      --hostname=localhost
      --hostname-strict=false" 
      --hostname-backchannel-dynamic=true
      --hostname-strict-backchannel=false
    environment:
      KC_HOSTNAME_PORT: 9000
      KC_DB_PASSWORD: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB: postgres
#      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_METRICS_ENABLED: "true"
      BOOTSTRAP_SERVERS: kafka-1:9090,kafka-2:9090,kafka-3:9090 #connection to kafka for spi
    ports:
      - "9000:8080"
    volumes:
      - ./providers:/opt/keycloak/providers
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "cat < /dev/null > /dev/tcp/localhost/8080" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 190s
    depends_on:
      keycloak-db:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    networks:
      - spring-market

  prometheus:
    user: "0:0"
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9410:9090"
    restart: on-failure
    networks:
      - spring-market
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/var/lib/prometheus
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    user: "0:0"
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      - spring-market
    volumes:
      - grafana_data:/var/lib/grafana
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      prometheus:
        condition: service_healthy

  grafana-loki:
    user: "0:0"
    image: grafana/loki:latest
    container_name: grafana-loki
    ports:
      - "3100:3100"
    restart: on-failure
    networks:
      - spring-market
    volumes:
      - loki_data:/var/lib/loki
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      prometheus:
        condition: service_healthy
      grafana:
        condition: service_healthy

  grafana-alloy:
    user: "0:0"
    image: grafana/alloy:latest
    container_name: grafana-alloy
    ports:
      - "12345:12345"
    restart: on-failure
    networks:
      - spring-market
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    healthcheck:
      test: ["CMD", "pgrep", "alloy"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      prometheus:
        condition: service_healthy
      grafana-loki:
        condition: service_healthy
      grafana:
        condition: service_healthy

  grafana-tempo:
    build:
      context: ./tempo
      dockerfile: Dockerfile
    user: "0:0"
    container_name: grafana-tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    restart: on-failure
    networks:
      - spring-market
    volumes:
      - tempo_data:/tmp/tempo
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3200/ready | grep -q 'ready' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: ["-config.file=/etc/tempo.yaml"]
    depends_on:
      prometheus:
        condition: service_healthy
      grafana:
        condition: service_healthy

  config-server:
    build:
      context: ./services/ConfigServer
      dockerfile: Dockerfile
    container_name: config-server
    user: "0:0"
    restart: on-failure
    ports:
      - "8888:8888"
    networks:
      - spring-market
    environment:
      SERVER_PORT: 8888
      SPRING_PROFILES_ACTIVE: native
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: config-server
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8888/actuator/health || exit 1"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./config:/config:rw
    depends_on:
      grafana-tempo:
        condition: service_healthy

  eureka-server:
    build:
      context: ./services/EurekaServer
      dockerfile: Dockerfile
    container_name: eureka-server
    restart: on-failure
    ports:
      - "8761:8761"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: cache,feign,jpa,kafka,mongo,security,dev
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: eureka-server
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8761/actuator/health || exit 1"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

  gateway:
    build:
      context: ./services/Gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    ports:
      - "8080:8080"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: cache,feign,jpa,kafka,mongo,security,eureka,dev
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: gateway
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      start_period: 180s
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

  analytic-service:
    build:
      context: ./services/AnalyticService
      dockerfile: Dockerfile
    container_name: analytic-service
    restart: on-failure
    ports:
      - "8085:8085"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: security,dev,kafka,cache,feign,jpa,mongo,eureka,security
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: analytic-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8085/actuator/health || exit 1"]
      interval: 10s
      timeout: 25s
      retries: 5
      start_period: 120s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

  cart-service:
    build:
      context: ./services/CartService
      dockerfile: Dockerfile
    container_name: cart-service
    restart: on-failure
    ports:
      - "8084:8084"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: cache,feign,jpa,kafka,mongo,security,eureka,dev
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: cart-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8084/actuator/health || exit 1"]
      interval: 10s
      timeout: 25s
      retries: 5
      start_period: 120s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

  category-service:
    build:
      context: ./services/CategoryService
      dockerfile: Dockerfile
    container_name: category-service
    restart: on-failure
    ports:
      - "8091:8091"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: cache,feign,jpa,kafka,mongo,security,eureka,dev
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: category-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8091/actuator/health || exit 1"]
      interval: 10s
      timeout: 25s
      retries: 5
      start_period: 120s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

  inventory-service:
    build:
      context: ./services/InventoryService
      dockerfile: Dockerfile
    container_name: inventory-service
    restart: on-failure
    ports:
      - "8087:8087"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: cache,feign,jpa,kafka,mongo,security,eureka,dev
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: inventory-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8087/actuator/health || exit 1"]
      interval: 10s
      timeout: 25s
      retries: 5
      start_period: 120s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

  notification-service:
    build:
      context: ./services/NotificationService
      dockerfile: Dockerfile
    container_name: notification-service
    restart: on-failure
    ports:
      - "8089:8089"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: cache,feign,jpa,kafka,mongo,security,eureka,dev
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: notification-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8089/actuator/health || exit 1"]
      interval: 10s
      timeout: 25s
      retries: 5
      start_period: 120s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

  order-service:
    build:
      context: ./services/OrderService
      dockerfile: Dockerfile
    container_name: order-service
    restart: on-failure
    ports:
      - "8082:8082"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: cache,feign,jpa,kafka,mongo,security,eureka,dev
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: order-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8082/actuator/health || exit 1"]
      interval: 10s
      timeout: 25s
      retries: 5
      start_period: 120s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

  payment-service:
    build:
      context: ./services/PaymentService
      dockerfile: Dockerfile
    container_name: payment-service
    env_file:
      - .env.local
    restart: on-failure
    ports:
      - "8088:8088"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: cache,feign,jpa,kafka,mongo,security,eureka,dev
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: payment-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8088/actuator/health || exit 1"]
      interval: 10s
      timeout: 25s
      retries: 5
      start_period: 120s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

  product-service:
    build:
      context: ./services/ProductService
      dockerfile: Dockerfile
    container_name: product-service
    restart: on-failure
    ports:
      - "8081:8081"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: cache,feign,jpa,kafka,mongo,security,eureka,dev
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: product-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 25s
      retries: 5
      start_period: 120s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

  review-service:
    build:
      context: ./services/ReviewService
      dockerfile: Dockerfile
    container_name: review-service
    restart: on-failure
    ports:
      - "8083:8083"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: cache,feign,jpa,kafka,mongo,security,eureka,dev
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: review-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8083/actuator/health || exit 1"]
      interval: 10s
      timeout: 25s
      retries: 5
      start_period: 120s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

  saga-service:
    build:
      context: ./services/SagaService
      dockerfile: Dockerfile
    container_name: saga-service
    restart: on-failure
    ports:
      - "8090:8090"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: cache,feign,jpa,kafka,mongo,security,eureka,dev
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: saga-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8090/actuator/health || exit 1"]
      interval: 10s
      timeout: 25s
      retries: 5
      start_period: 120s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

  user-service:
    build:
      context: ./services/UserService
      dockerfile: Dockerfile
    container_name: user-service
    restart: on-failure
    ports:
      - "8086:8086"
    networks:
      - spring-market
    environment:
      SPRING_PROFILES_ACTIVE: cache,feign,jpa,kafka,mongo,security,eureka,dev
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: user-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_TRACES_EXPORTER: otlp,logging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-tempo:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_LOGS_EXPORTER: logging
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS: /actuator/**
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8086/actuator/health || exit 1"]
      interval: 10s
      timeout: 25s
      retries: 5
      start_period: 120s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis:
        condition: service_healthy
      grafana-tempo:
        condition: service_healthy

volumes:
  keycloak_data:
    driver: local
  redis_data:
  mongo_data:
  postgres_data:
  kafka-1_data:
  kafka-2_data:
  kafka-3_data:
  debezium_data:
  prometheus_data:
    driver: local
  grafana_data:
  loki_data:
  alloy_data:
  tempo_data: