CREATE DATABASE cart_db;
CREATE DATABASE order_db;
CREATE DATABASE payment_db;
CREATE DATABASE product_db;
CREATE DATABASE review_db;
CREATE DATABASE user_db;

CREATE USER cart_service WITH PASSWORD 'cart_pass';
CREATE USER order_service WITH PASSWORD 'order_pass';
CREATE USER payment_service WITH PASSWORD 'payment_pass';
CREATE USER product_service WITH PASSWORD 'product_pass';
CREATE USER review_service WITH PASSWORD 'review_pass';
CREATE USER user_service WITH PASSWORD 'user_pass';

GRANT ALL PRIVILEGES ON DATABASE cart_db TO cart_service;
GRANT ALL PRIVILEGES ON DATABASE order_db TO order_service;
GRANT ALL PRIVILEGES ON DATABASE payment_db TO payment_service;
GRANT ALL PRIVILEGES ON DATABASE product_db TO product_service;
GRANT ALL PRIVILEGES ON DATABASE review_db TO review_service;
GRANT ALL PRIVILEGES ON DATABASE user_db TO user_service;

\c cart_db;
CREATE SCHEMA cart_schema;
GRANT ALL ON SCHEMA public TO cart_service;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO cart_service;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO cart_service;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO cart_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO cart_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO cart_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO cart_service;

GRANT ALL ON SCHEMA cart_schema TO cart_service;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA cart_schema TO cart_service;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA cart_schema TO cart_service;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA cart_schema TO cart_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA cart_schema GRANT ALL ON TABLES TO cart_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA cart_schema GRANT ALL ON SEQUENCES TO cart_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA cart_schema GRANT ALL ON FUNCTIONS TO cart_service;

\c order_db;
CREATE SCHEMA order_schema;
GRANT ALL ON SCHEMA public TO order_service;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO order_service;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO order_service;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO order_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO order_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO order_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO order_service;

GRANT ALL ON SCHEMA order_schema TO order_service;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA order_schema TO order_service;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA order_schema TO order_service;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA order_schema TO order_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA order_schema GRANT ALL ON TABLES TO order_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA order_schema GRANT ALL ON SEQUENCES TO order_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA order_schema GRANT ALL ON FUNCTIONS TO order_service;

\c payment_db;
CREATE SCHEMA payment_schema;
GRANT ALL ON SCHEMA public TO payment_service;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO payment_service;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO payment_service;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO payment_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO payment_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO payment_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO payment_service;

GRANT ALL ON SCHEMA payment_schema TO payment_service;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA payment_schema TO payment_service;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA payment_schema TO payment_service;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA payment_schema TO payment_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA payment_schema GRANT ALL ON TABLES TO payment_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA payment_schema GRANT ALL ON SEQUENCES TO payment_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA payment_schema GRANT ALL ON FUNCTIONS TO payment_service;

\c product_db;
CREATE SCHEMA product_schema;
GRANT ALL ON SCHEMA public TO product_service;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO product_service;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO product_service;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO product_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO product_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO product_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO product_service;

GRANT ALL ON SCHEMA product_schema TO product_service;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA product_schema TO product_service;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA product_schema TO product_service;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA product_schema TO product_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA product_schema GRANT ALL ON TABLES TO product_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA product_schema GRANT ALL ON SEQUENCES TO product_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA product_schema GRANT ALL ON FUNCTIONS TO product_service;

\c review_db;
CREATE SCHEMA review_schema;
GRANT ALL ON SCHEMA public TO review_service;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO review_service;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO review_service;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO review_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO review_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO review_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO review_service;

GRANT ALL ON SCHEMA review_schema TO review_service;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA review_schema TO review_service;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA review_schema TO review_service;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA review_schema TO review_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA review_schema GRANT ALL ON TABLES TO review_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA review_schema GRANT ALL ON SEQUENCES TO review_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA review_schema GRANT ALL ON FUNCTIONS TO review_service;

\c user_db;
CREATE SCHEMA user_schema;
GRANT ALL ON SCHEMA public TO user_service;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO user_service;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO user_service;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO user_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO user_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO user_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO user_service;

GRANT ALL ON SCHEMA user_schema TO user_service;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA user_schema TO user_service;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA user_schema TO user_service;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA user_schema TO user_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA user_schema GRANT ALL ON TABLES TO user_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA user_schema GRANT ALL ON SEQUENCES TO user_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA user_schema GRANT ALL ON FUNCTIONS TO user_service;