apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: category-service
    environment: default
  name: category-service-config
  namespace: spring-market
data:
  application.yaml: |-
    server:
      port: 8091
      shutdown: graceful

    springdoc:
      api-docs:
        path: /category-service/v3/api-docs
      swagger-ui:
        path: /category-service/swagger-ui.html