apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-service
  name: product-service
  namespace: spring-market
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: product-service
  type: ClusterIP