apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |-
    server:
      port: {{ index .Values.spring.services "user-service" "port" }}
      shutdown: graceful

    springdoc:
      api-docs:
        path: /user-service/v3/api-docs
      swagger-ui:
        path: /user-service/swagger-ui.html