apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debezium-data
  namespace: messaging
  labels:
    app: debezium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
