apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-market
  name: config-server
  labels:
    app: config-server
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
        version: v1

    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: config-server
          volumeMounts:
            - name: services-config
              mountPath: /app/config/services
              readOnly: true
            - name: config-server-config
              mountPath: /app/config/source-config
              readOnly: true

          env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/app/opentelemetry-javaagent.jar
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://grafana-tempo.observability.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS
              value: /actuator/**
            - name: OTEL_LOGS_EXPORTER
              value: logging
            - name: OTEL_METRICS_EXPORTER
              value: prometheus
            - name: OTEL_SERVICE_NAME
              value: config-server
            - name: OTEL_SERVICE_VERSION
              value: 1.0.0
            - name: OTEL_TRACES_EXPORTER
              value: otlp,logging
            - name: SERVER_PORT
              value: "8888"
            - name: SPRING_PROFILES_ACTIVE
              value: native
            - name: SPRING_CONFIG_LOCATION
              value: optional:file:/app/config/source-config/


          image: ghcr.io/cryptic901/springmarket/config-server:develop-2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
            - name: metrics
              containerPort: 9464
              protocol: TCP
          restartPolicy: Always

          livenessProbe:
            httpGet:
              port: 8888
              path: /actuator/health/liveness
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              port: 8888
              path: /actuator/health/readiness
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 3

          startupProbe:
            httpGet:
              port: 8888
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            failureThreshold: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5

          resources:
            requests:
              memory: "150Mi"
              cpu: "150m"
            limits:
              memory: "400Mi"
              cpu: "350m"
      volumes:
        - name: config-server-config
          configMap:
            name: config-server-configmap

        - name: services-config
          projected:
            sources:
              - configMap:
                  name: application-configmap
              - configMap:
                  name: analytic-server-configmap
              - configMap:
                  name: cart-service-configmap
              - configMap:
                  name: category-service-configmap
              - configMap:
                  name: eureka-server-configmap
              - configMap:
                  name: gateway-configmap
              - configMap:
                  name: inventory-service-configmap
              - configMap:
                  name: notification-service-configmap
              - configMap:
                  name: order-service-configmap
              - configMap:
                  name: payment-service-configmap
              - configMap:
                  name: product-service-configmap
              - configMap:
                  name: review-service-configmap
              - configMap:
                  name: saga-service-configmap
              - configMap:
                  name: user-service-configmap
