spring:
  application:
    name: SpringMarket
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringMarket
    username: admin
    password: $2a$12$WHDRyXGTErJoxwlXnU7tquYrgnSaPoh5D.iCmqnNk17Mdsii17CZO
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
  security:
    user:
      password: password
      name: user
    jwt:
      secret: G7nHsKi/JvNfskJg4m4bbq2KqQOuvPWXAzTyOq7SmQA=
      expiration: 1h
  mail:
    password: ywre dqkk oevd lelo
    username: luckyartem901@gmail.com
  kafka:
    consumer:
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: by.cryptic.springmarket.*
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC

logging:
  level:
    org:
      springframework:
        cache: TRACE
        web: TRACE
        http: TRACE
        security: trace