spring:
  application:
    name: OrderService
  cloud:
    config:
      profile: dev
      username: config
      password: config
  config:
    import: "optional:configserver:http://config-server:8888"



