apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: payment-service
  name: payment-service-cache
  namespace: spring-market
data:
  application.yaml: |
    spring:
      cache:
        enabled: true
      data:
        redis:
          host: redis.database.svc.cluster.local
          port: 6379