apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: payment-service
  name: payment-service-cache
  namespace: spring-market
data:
  application.yaml: |
    spring:
      cache:
        enabled: true