{{- range $serviceName, $service := .Values.spring.services -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-market
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
    version: v1
spec:
  replicas: {{ $service.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
        version: v1
    spec:
      serviceAccountName: spring-services-sa
      restartPolicy: Always
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -XX:ActiveProcessorCount=2 -XX:MaxRAMPercentage=70.0 -javaagent:/app/opentelemetry-javaagent.jar
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://grafana-tempo.observability.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS
              value: /actuator/**
            - name: OTEL_LOGS_EXPORTER
              value: logging
            - name: OTEL_METRICS_EXPORTER
              value: prometheus
            - name: OTEL_SERVICE_NAME
              value: {{ $serviceName }}
            - name: OTEL_SERVICE_VERSION
              value: 1.0.0
            - name: OTEL_TRACES_EXPORTER
              value: otlp,logging
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $service.profiles }}

          image: {{ $service.image }}:develop-0167b3b
          imagePullPolicy: IfNotPresent
          name: {{ $serviceName }}
          ports:
            - name: http
              containerPort: {{ $service.port }}
              protocol: TCP
            - name: metrics
              containerPort: 9464
              protocol: TCP

          livenessProbe:
            httpGet:
              port: {{ $service.port }}
              path: /actuator/health/liveness
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              port: {{ $service.port }}
              path: /actuator/health/readiness
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 3

          startupProbe:
            httpGet:
              port: {{ $service.port }}
              path: /actuator/health/liveness
            initialDelaySeconds: 20
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5

          resources:
            requests:
              memory: {{ $service.resources.requests.memory }}
              cpu: {{ $service.resources.requests.cpu }}
            limits:
              memory: {{ $service.resources.limits.memory }}
              cpu: {{ $service.resources.limits.cpu }}
  {{- end }}