apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-market
  name: saga-service
  labels:
    app: saga-service
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: saga-service
  template:
    metadata:
      labels:
        app: saga-service
        version: v1

    spec:
      serviceAccountName: spring-services-sa
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/app/opentelemetry-javaagent.jar
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://grafana-tempo.observability.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS
              value: /actuator/**
            - name: OTEL_LOGS_EXPORTER
              value: logging
            - name: OTEL_METRICS_EXPORTER
              value: prometheus
            - name: OTEL_SERVICE_NAME
              value: saga-service
            - name: OTEL_SERVICE_VERSION
              value: 1.0.0
            - name: OTEL_TRACES_EXPORTER
              value: otlp,logging
            - name: SPRING_PROFILES_ACTIVE
              value: dev

          image: ghcr.io/cryptic901/springmarket/saga-service:develop-latest
          imagePullPolicy: IfNotPresent
          name: saga-service
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
            - name: metrics
              containerPort: 9464
              protocol: TCP
          restartPolicy: Always

          livenessProbe:
            httpGet:
              port: 8090
              path: /actuator/health/liveness
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              port: 8090
              path: /actuator/health/readiness
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 3

          startupProbe:
            httpGet:
              port: 8090
              path: /actuator/health/liveness
            initialDelaySeconds: 20
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5

          resources:
            requests:
              memory: "350Mi"
              cpu: "250m"
            limits:
              memory: "550Mi"
              cpu: "400m"
