apiVersion: v1
kind: Service
metadata:
  labels:
    app: saga-service
  name: saga-service
  namespace: spring-market
spec:
  ports:
    - name: http
      port: 8090
      targetPort: 8090
  selector:
    app: saga-service
  type: ClusterIP