apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tempo
  name: tempo-data
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
