apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: analytic-service
    environment: default
  name: analytic-service-config
  namespace: spring-market
data:
  application.yaml: |-
    server:
      port: 8085
      shutdown: graceful

    spring:
      application:
        name: analytic-service
      cloud:
        kubernetes:
          enabled: true
          reload:
            enabled: true
            mode: polling
            period: 5000

    springdoc:
      api-docs:
        path: /analytic-service/v3/api-docs
      swagger-ui:
        path: /analytic-service/swagger-ui.html