apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: analytic-service
  name: analytic-service-security
  namespace: spring-market
data:
  application.yaml: |-
    spring:
      security:
        enabled: true
