apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: analytic-service
  name: analytic-service-kubernetes
  namespace: spring-market
data:
  application.yaml: |-
    server:
      port: 8085
      shutdown: graceful

    springdoc:
      api-docs:
        path: /analytic-service/v3/api-docs
      swagger-ui:
        path: /analytic-service/swagger-ui.html