{{- range $serviceName, $service := .Values.database.services -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ $serviceName }}
spec:
  ports:
    - name: {{ $serviceName }}
      port: {{ $service.port }}
      targetPort: {{ $service.targetPort }}
  selector:
    app: {{ $serviceName }}

  {{- end}}