apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: user-service
  name: user-service-kubernetes
  namespace: spring-market
data:
  application.yaml: |-
    server:
      port: 8086
      shutdown: graceful

    springdoc:
      api-docs:
        path: /user-service/v3/api-docs
      swagger-ui:
        path: /user-service/swagger-ui.html