apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: order-service
  name: order-service
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |-
    server:
      port: {{ index .Values.spring.services.orderService.port }}
      shutdown: graceful

    springdoc:
      api-docs:
        path: /order-service/v3/api-docs
      swagger-ui:
        path: /order-service/swagger-ui.html