apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: gateway
    environment: default
  name: gateway-config
  namespace: spring-market
data:
  application.yaml: |-
    server:
      port: 8080
      shutdown: graceful
    eureka:
      instance:
        hostname: gateway
        prefer-ip-address: false
    springdoc:
      api-docs:
        enabled: true
      swagger-ui:
        urls:
          - name: UserService
            url: /user-service/v3/api-docs

          - name: ReviewService
            url: /review-service/v3/api-docs

          - name: ProductService
            url: /product-service/v3/api-docs

          - name: PaymentService
            url: /payment-service/v3/api-docs

          - name: OrderService
            url: /order-service/v3/api-docs

          - name: CategoryService
            url: /category-service/v3/api-docs

          - name: CartService
            url: /cart-service/v3/api-docs

          - name: AnalyticService
            url: /analytic-service/v3/api-docs

          - name: InventoryService
            url: /inventory-service/v3/api-docs
    spring:
      security:
        oauth2:
          client:
            provider:
              keycloak:
                authorization-uri: http://keycloak.keycloak.svc.cluster.local:8080/realms/springmarket/protocol/openid-connect/auth
                token-uri: http://keycloak.keycloak.svc.cluster.local:8080/realms/springmarket/protocol/openid-connect/token
                user-info-uri: http://keycloak.keycloak.svc.cluster.local:8080/realms/springmarket/protocol/openid-connect/userinfo
                jwk-set-uri: http://keycloak.keycloak.svc.cluster.local:8080/realms/springmarket/protocol/openid-connect/certs

            registration:
              keycloak:
                client-id: api-gateway
                client-secret: iUoy91EYLWU4q3cdtjdTzMd3d7iqJ1VL
                scope: openid,email,profile
                authorization-grant-type: authorization_code
                redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      cloud:
        discovery:
          enabled: true
        gateway:
          routes:
            - id: product-routes
              uri: lb://PRODUCTSERVICE
              predicates:
                - Path=/api/v1/products/**
              filters:
                - TokenRelay

            - id: product-docs
              uri: lb://PRODUCTSERVICE
              predicates:
                - Path=/product-service/v3/api-docs

            - id: category-routes
              uri: lb://CATEGORYSERVICE
              predicates:
                - Path=/api/v1/categories/**
              filters:
                - TokenRelay

            - id: category-docs
              uri: lb://CATEGORYSERVICE
              predicates:
                - Path=/category-service/v3/api-docs

            - id: order-routes
              uri: lb://ORDERSERVICE
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - TokenRelay

            - id: order-docs
              uri: lb://ORDERSERVICE
              predicates:
                - Path=/order-service/v3/api-docs

            - id: inventory-routes
              uri: lb://INVENTORYSERVICE
              predicates:
                - Path=/api/v1/inventories/**
              filters:
                - TokenRelay

            - id: warehouse-routes
              uri: lb://INVENTORYSERVICE
              predicates:
                - Path=/api/v1/warehouses/**
              filters:
                - TokenRelay

            - id: inventory-docs
              uri: lb://INVENTORYSERVICE
              predicates:
                - Path=/inventory-service/v3/api-docs

            - id: review-routes
              uri: lb://REVIEWSERVICE
              predicates:
                - Path=/api/v1/reviews/**
              filters:
                - TokenRelay

            - id: review-docs
              uri: lb://REVIEWSERVICE
              predicates:
                - Path=/review-service/v3/api-docs

            - id: user-routes
              uri: lb://USERSERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - TokenRelay

            - id: user-docs
              uri: lb://USERSERVICE
              predicates:
                - Path=/user-service/v3/api-docs

            - id: payment-routes
              uri: lb://PAYMENTSERVICE
              predicates:
                - Path=/api/v1/payments/**
              filters:
                - TokenRelay

            - id: payment-docs
              uri: lb://PAYMENTSERVICE
              predicates:
                - Path=/payment-service/v3/api-docs

            - id: notification-routes
              uri: lb://NOTIFICATIONSERVICE
              predicates:
                - Path=/api/v1/notifications/**
              filters:
                - TokenRelay

            - id: analytic-routes
              uri: lb://ANALYTICSERVICE
              predicates:
                - Path=/api/v1/admin/**
              filters:
                - TokenRelay

            - id: analytic-docs
              uri: lb://ANALYTICSERVICE
              predicates:
                - Path=/analytic-service/v3/api-docs

            - id: cart-routes
              uri: lb://CARTSERVICE
              predicates:
                - Path=/api/v1/carts/**
              filters:
                - TokenRelay

            - id: cart-docs
              uri: lb://CARTSERVICE
              predicates:
                - Path=/cart-service/v3/api-docs

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true