apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: review-service
  name: review-service-mongo
  namespace: spring-market
data:
  application.yaml: |-
    spring:
      mongo:
        enabled: true
      data:
        mongodb:
          uri: mongodb://mongo.database.svc.cluster.local:27017/reviewDB
