apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: review-service
  name: review-service-jpa
  namespace: spring-market
data:
  application.yaml: |-
    spring:
      datasource:
        url: jdbc:postgresql://postgres.database.svc.cluster.local:5432/review_db
        username: review_service
        password: review_pass
      jpa:
        enabled: true
        hibernate:
          ddl-auto: update
      flyway:
        schemas: review_schema
        default-schema: review_schema
        enabled: true
        baseline-on-migrate: true