apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: review-service
  name: review-service
  namespace: spring-market
data:
  application.yaml: |-
    server:
      port: 8083
      shutdown: graceful

    springdoc:
      api-docs:
        path: /review-service/v3/api-docs
      swagger-ui:
        path: /review-service/swagger-ui.html