apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: product-service
  name: product-service-feign
  namespace: spring-market
data:
  application.yaml: |-
    spring:
     feign:
       enabled: true