apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: product-service
  name: product-service-jpa
  namespace: spring-market
data:
  application.yaml: |-
    spring:
      datasource:
        url: jdbc:postgresql://postgres.database.svc.cluster.local:5432/product_db
        username: product_service
        password: product_pass
      flyway:
        schemas: product_schema
        default-schema: product_schema
        enabled: true
        baseline-on-migrate: true
      jpa:
        enabled: true
        hibernate:
          ddl-auto: update
          hibernate:
            jdbc:
              batch_size: 50
            order_updates: true
            order_inserts: true
        path: /product-service/swagger-ui.html