apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: order-service
  name: order-service-cache
  namespace: spring-market
data:
  application.yaml: |-
    spring:
      cache:
        enabled: true