apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: review-service
  name: review-service
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |-
    server:
      port: {{ index .Values.spring.services.reviewService.port }}
      shutdown: graceful

    springdoc:
      api-docs:
        path: /review-service/v3/api-docs
      swagger-ui:
        path: /review-service/swagger-ui.html