apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: keycloak
      port: {{ .Values.auth.services.keycloak.port }}
      targetPort: {{ .Values.auth.services.keycloak.targetPort }}
  selector:
    app: keycloak
