spring:
  config:
    import: "optional:kubernetes:"
  application:
    name: payment-service
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        enabled: true
        sources:
          - namespace: spring-market
            name: common-config

          - namespace: spring-market
            name: payment-service

          - namespace: spring-market
            name: payment-service-cache

          - namespace: spring-market
            name: payment-service-kafka

          - namespace: spring-market
            name: payment-service-security

          - namespace: spring-market
            name: payment-service-jpa

          - namespace: spring-market
            name: payment-service-mongo











