apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: messaging
  labels:
    app: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:latest
          ports:
            - containerPort: 9090
              name: client
            - containerPort: 9091
              name: controller
        - env:
            - name: CLUSTER_ID
              value: MkU3OEVBNTcwNTJENDM2Qk
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://$(POD_NAME).kafka-headless.messaging.svc.cluster.local:9090
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-0.kafka-headless.messaging.svc.cluster.local:9091,
              1@kafka-1.kafka-headless.messaging.svc.cluster.local:9091,
              2@kafka-2.kafka-headless.messaging.svc.cluster.local:9091"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9090,CONTROLLER://:9091
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_LOG_DIRS
              value: /var/lib/kafka/data
            - name: KAFKA_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_PROCESS_ROLES
              value: controller,broker
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - >
                  NODE_ID=$(echo $POD_NAME | grep -o '[0-9]\+$') &&
                  /opt/kafka/bin/kafka-metadata-quorum.sh --bootstrap-server localhost:9090 describe --status
            failureThreshold: 5
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 60

          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "750m"

          name: kafka
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka-data

      restartPolicy: Always
      terminationGracePeriodSeconds: 30

  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
