apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: saga-service
  name: saga-service-kubernetes
  namespace: spring-market
data:
  application.yaml: |
    server:
      port: 8090
      shutdown: graceful