apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: inventory-service
  name: inventory-service-security
  namespace: spring-market
data:
  application.yaml: |-
    spring:
      security:
        enabled: true