apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: inventory-service
    environment: default
  name: inventory-service-config
  namespace: spring-market
data:
  application.yaml: |-
    server:
      port: 8087
      shutdown: graceful

    springdoc:
      api-docs:
        path: /inventory-service/v3/api-docs
      swagger-ui:
        path: /inventory-service/swagger-ui.html