apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: spring-market
  name: spring-services-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spring-market
  name: config-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-market-rolebinding
  namespace: spring-market
subjects:
  - kind: ServiceAccount
    name: spring-services-sa
    namespace: spring-market
roleRef:
  kind: Role
  name: config-role
  apiGroup: rbac.authorization.k8s.io