apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  namespace: database
  labels:
    app: keycloak-db
spec:
  ports:
    - name: keycloak-db
      port: 5400
      targetPort: 5432
  selector:
    app: keycloak-db
