apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: keycloak-db
  name: keycloak-db
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:18-alpine

          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres -d keycloak
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            exec:
              command: [ "pg_isready", "-U", "postgres" ]
            initialDelaySeconds: 5
            periodSeconds: 5

          name: keycloak-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: keycloak-data

          resources:
            requests:
              memory: "250Mi"
              cpu: "125m"
            limits:
              memory: "500Mi"
              cpu: "350m"

  volumeClaimTemplates:
    - metadata:
        name: keycloak-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard

