spring:
  application:
    name: NotificationService
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev
      username: config
      password: config
server:
  port: 8089
