eureka:
  instance:
    hostname: analytic-service
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    should-unregister-on-shutdown: false