spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/springmarket/protocol/openid-connect/certs
resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.sql.SQLException
          - java.net.ConnectException
          - jakarta.ws.rs.ProcessingException
          - org.springframework.web.client.HttpClientErrorException
          - org.springframework.dao.TransientDataAccessResourceException
        ignore-exceptions:
          - by.cryptic.exceptions.UpdatingException
          - by.cryptic.exceptions.DeletingException
          - by.cryptic.exceptions.CreatingException
          - java.lang.IllegalArgumentException
          - java.lang.IllegalStateException
          - java.lang.NullPointerException
          - org.springframework.dao.DataIntegrityViolationException
          - jakarta.persistence.EntityNotFoundException
    instances:
      productRetry:
        baseConfig: default
      reviewRetry:
        baseConfig: default
      orderRetry:
        baseConfig: default
      cartRetry:
        baseConfig: default

  circuitbreaker:
    configs:
      default:
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
        ignore-exceptions:
          - by.cryptic.exceptions.EmptyCartException
          - jakarta.persistence.EntityNotFoundException
          - java.lang.IllegalStateException
    instances:
      orderCircuitBreaker:
        baseConfig: default
      cartCircuitBreaker:
        baseConfig: default
      productCircuitBreaker:
        baseConfig: default

  ratelimiter:
    configs:
      default:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 10s
        register-health-indicator: true
    instances:
      paymentRatelimiter:
        baseConfig: default


managment:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
  health:
    ratelimiters:
      enabled: true
  info:
    env:
      enabled: true
logging:
  level:
    io.github.resilience4j: DEBUG
    org:
      springframework:
        cache: INFO
        web: INFO
        http: INFO
        security: DEBUG
        security.oauth2.jwt: DEBUG
        security.oauth2.server.resource: DEBUG
        kafka: INFO
      apache:
        kafka: INFO
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId},%X{spanId}] %-5level %logger{36} - %msg%n"