eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI:http://localhost:9000/realms/springmarket}
resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.sql.SQLException
          - java.net.ConnectException
          - jakarta.ws.rs.ProcessingException
          - org.springframework.web.client.HttpClientErrorException
          - org.springframework.dao.TransientDataAccessResourceException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
          - java.lang.IllegalStateException
          - java.lang.NullPointerException
          - org.springframework.dao.DataIntegrityViolationException
          - jakarta.persistence.EntityNotFoundException
          - java.lang.RuntimeException
    instances:
      productRetry:
        baseConfig: default
      reviewRetry:
        baseConfig: default
      orderRetry:
        baseConfig: default
      cartRetry:
        baseConfig: default

  circuitbreaker:
    configs:
      default:
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
        ignore-exceptions:
          - by.cryptic.exceptions.EmptyCartException
          - jakarta.persistence.EntityNotFoundException
          - java.lang.IllegalStateException
    instances:
      orderCircuitBreaker:
        baseConfig: default
      cartCircuitBreaker:
        baseConfig: default

  bulkhead:
    configs:
      default:
        max-concurrent-calls: 5
        max-wait-duration: 100ms
    instances:
      productBulkhead:
        baseConfig: default
      reviewBulkhead:
        baseConfig: default
      orderBulkhead:
        baseConfig: default
      cartBulkhead:
        baseConfig: default


management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
logging:
  level:
    org:
      springframework:
        cache: DEBUG
        web: DEBUG
        http: DEBUG
        security: DEBUG
        kafka: DEBUG
      apache:
        kafka: DEBUG
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId},%X{spanId}] %-5level %logger{36} - %msg%n"