eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org:
      springframework:
        cache: INFO
        web: INFO
        http: INFO
        security: INFO