spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cart_db
    username: cart_service
    password: cart_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: cart_schema
    default-schema: cart_schema
    enabled: true
    baseline-on-migrate: true