spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/category_db
    username: category_service
    password: category_pass

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    schemas: category_schema
    default-schema: category_schema
    enabled: true
    baseline-on-migrate: true