server:
  port: 8080
eureka:
  instance:
    hostname: gateway
    prefer-ip-address: false
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://keycloak:8080/realms/springmarket/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/springmarket/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/springmarket/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/springmarket/protocol/openid-connect/certs
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: 1tqdg0yCH9sTJ6P9fmLYeExji2I64ZwP
            scope: openid,email,profile
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: product-routes
          uri: lb://ProductService
          predicates:
            - Path=/api/v1/products/**
            - Path=/api/v1/categories/**
          filters:
            - TokenRelay

        - id: order-routes
          uri: lb://OrderService
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - TokenRelay

        - id: cart-routes
          uri: lb://CartService
          predicates:
            - Path=/api/v1/carts/**
          filters:
            - TokenRelay

        - id: review-routes
          uri: lb://ReviewService
          predicates:
            - Path=/api/v1/reviews/**
          filters:
            - TokenRelay

        - id: user-routes
          uri: lb://UserService
          predicates:
            - Path=/api/v1/users/**
          filters:
            - TokenRelay

        - id: payment-routes
          uri: lb://PaymentService
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - TokenRelay

        - id: notification-routes
          uri: lb://NotificationService
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - TokenRelay

        - id: analytic-routes
          uri: lb://AnalyticService
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - TokenRelay

        - id: keycloak-routes
          uri: http://keycloak:8080
          predicates:
            - Path=/realms/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true