server:
  port: 8080
eureka:
  instance:
    hostname: gateway
    prefer-ip-address: false
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI:http://keycloak:8080/realms/springmarket}
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: ocv0FnSgjzQ3IYKRusilob1tMoY8FSw4
            scope:
              - openid
              - email
              - profile
            authorization-grant-type: authorization_code
            redirect-uri: {$KEYCLOAK_REDIRECT_URI:http://localhost:9000/login/oauth2/code/keycloak}
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: product-routes
          uri: lb://ProductService
          predicates:
            - Path=/api/v1/products/**
            - Path=/api/v1/categories/**

        - id: order-routes
          uri: lb://OrderService
          predicates:
            - Path=/api/v1/orders/**

        - id: cart-routes
          uri: lb://CartService
          predicates:
            - Path=/api/v1/carts/**

        - id: review-routes
          uri: lb://ReviewService
          predicates:
            - Path=/api/v1/reviews/**

        - id: user-routes
          uri: lb://UserService
          predicates:
            - Path=/api/v1/users/**

        - id: payment-routes
          uri: lb://PaymentService
          predicates:
            - Path=/api/v1/payments/**

        - id: notification-routes
          uri: lb://NotificationService
          predicates:
            - Path=/api/v1/notifications/**

        - id: analytic-routes
          uri: lb://AnalyticService
          predicates:
            - Path=/api/v1/admin/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay