server:
  port: 8088
  shutdown: graceful

springdoc:
  api-docs:
    path: /payment-service/v3/api-docs
  swagger-ui:
    path: /payment-service/swagger-ui.html

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}

