spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/product_db
    username: product_service
    password: product_pass
  flyway:
    schemas: product_schema
    default-schema: product_schema
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true