spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/review_db
    username: review_service
    password: review_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: review_schema
    default-schema: review_schema
    enabled: true
    baseline-on-migrate: true