apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
  name: notification-service
  namespace: spring-market
spec:
  ports:
    - name: http
      port: 8089
      targetPort: 8089
  selector:
    app: notification-service
  type: ClusterIP