apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: database
  labels:
   app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:8.2.2

          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 5

          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: redis-data

          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

      restartPolicy: Always

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
