spring:
  config:
    import: "optional:kubernetes:"
  application:
    name: analytic-service
  profiles:
    group:
      dev: "security,kafka,cache"
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        enabled: true
        sources:
          - namespace: spring-market
            name: common-config-dev

          - namespace: spring-market
            name: analytic-service-dev

          - namespace: spring-market
            name: analytic-service-cache

          - namespace: spring-market
            name: analytic-service-kafka

          - namespace: spring-market
            name: analytic-service-security