spring:
  config:
    import: "optional:kubernetes:"
  application:
    name: analytic-service
  profiles:
    group:
      dev: "security,kafka,cache"
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        enabled: true
        sources:
          - namespace: spring-market
            name: common-config
          - namespace: spring-market
            name: common-config-${spring.profiles.active}
          - namespace: spring-market
            name: analytic-service
          - namespace: spring-market
            name: analytic-service-${spring.profiles.active}