spring:
  config:
    import: "optional:kubernetes:"
  application:
    name: order-service
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        enabled: true
        include-profile-specific-sources: false
        sources:
          - namespace: spring-market
            name: common-config

          - namespace: spring-market
            name: order-service

          - namespace: spring-market
            name: order-service-cache

          - namespace: spring-market
            name: order-service-kafka

          - namespace: spring-market
            name: order-service-security

          - namespace: spring-market
            name: order-service-feign

          - namespace: spring-market
            name: order-service-jpa

          - namespace: spring-market
            name: order-service-mongo



