apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: notification-service
  name: notification-service-security
  namespace: spring-market
data:
  application.yaml: |
    spring:
     security:
       enabled: true