apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: notification-service
    environment: default
  name: notification-service-config
  namespace: spring-market
data:
  application.yaml: |
    server:
      port: 8089
      shutdown: graceful

    spring:
      mail:
        password: ywre dqkk oevd lelo
        username: luckyartem901@gmail.com