### Get All Orders
GET {{host}}/api/v1/orders
Accept: application/json
Authorization: Bearer {{authToken}}

### Get Order By ID
GET {{host}}/api/v1/orders/{{orderId}}
Accept: application/json
Authorization: Bearer {{authToken}}

### Create Order
POST {{host}}/api/v1/orders
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "location": "city Gomel"
}

### Cancel Order
PATCH {{host}}/api/v1/orders/cancel/{{orderId}}
Authorization: Bearer {{authToken}}
