### Get All Orders
GET {{host}}/api/v1/orders
Accept: application/json
Authorization: Bearer {{authToken}}

### Get Order By ID
@orderId = variable value
GET {{host}}/api/v1/orders/{{orderId}}
Accept: application/json
Authorization: Bearer {{authToken}}

### Create Order
POST {{host}}/api/v1/orders
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "location": "city Gomel"
}

### Update Order
@updateOrderId = variable value
PATCH {{host}}/api/v1/orders/{updateOrderId}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "location": "new location"
}

### Cancel Order
@cancelOrderId = variable value
PATCH {{host}}/api/v1/orders/cancel/{{cancelOrderId}}
Authorization: Bearer {{authToken}}
