apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: cart-service
  name: cart-service-feign
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |-
    spring:
      feign:
        enabled: true