{{- range $serviceName, $service := .Values.observability.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $serviceName }}
spec:
  selector:
    app: {{ $serviceName }}
  ports:
{{- if $service.port }}
    - name: http
      port: {{ $service.port }}
      targetPort: {{ $service.targetPort }}
      protocol: TCP
{{- end }}
{{- if $service.ports }}
  {{- range $portName, $portNumber := $service.ports }}
    - name: {{ $portName }}
      port: {{ $portNumber }}
      targetPort: {{ $portNumber }}
      protocol: TCP
  {{- end }}
{{- end }}
{{- end }}