database:
  services:
    keycloak-db:
      port: 5400
      targetPort: 5432
      replicaCount: 1

    mongo:
      port: 27017
      targetPort: 27017
      replicaCount: 1

    postgres:
      port: 5432
      targetPort: 5432
      replicaCount: 1

    redis:
      port: 6379
      targetPort: 6379
      replicaCount: 1

global:
  namespace: messaging

debezium:
  defaults:
    database:
      host: postgres.database.svc.cluster.local
      port: "5432"
      user: postgres
      password: postgres

  kafka:
    bootstrapServers: "kafka-0.kafka-headless.messaging.svc.cluster.local:9090,kafka-1.kafka-headless.messaging.svc.cluster.local:9090,kafka-2.kafka-headless.messaging.svc.cluster.local:9090"

  connectors:
    cart:
      database:
        name: cart_db
      table: cart_schema.outbox
      additionalPlacement: "event_type:header:eventType,aggregate_id:header:aggregateId"

    category:
      database:
        name: category_db
      table: category_schema.outbox

    inventory:
      database:
        name: inventory_db
      table: inventory_schema.outbox
      additionalPlacement: "event_type:header:eventType,aggregate_id:header:aggregateId"

    order:
      database:
        name: order_db
      table: order_schema.outbox
      additionalPlacement: "event_type:header:eventType,aggregate_id:header:aggregateId"

    payment:
      database:
        name: payment_db
      table: payment_schema.outbox
      additionalPlacement: "event_type:header:eventType,aggregate_id:header:aggregateId"

    product:
      database:
        name: product_db
      table: product_schema.outbox
      additionalPlacement: "event_type:header:eventType,aggregate_id:header:aggregateId"

    review:
      database:
        name: review_db
      table: review_schema.outbox
      additionalPlacement: "event_type:header:eventType,aggregate_id:header:aggregateId"


postgres:
  database:
    cart:
      name: cart_db
      schema: cart_schema
      username: cart_service
      password: 'cart_pass'

    category:
      name: category_db
      schema: category_schema
      username: category_service
      password: 'category_pass'

    inventory:
      name: inventory_db
      schema: inventory_schema
      username: inventory_service
      password: 'inventory_pass'

    order:
      name: order_db
      schema: order_schema
      username: order_service
      password: 'order_pass'

    payment:
      name: payment_db
      schema: payment_schema
      username: payment_service
      password: 'payment_pass'

    product:
      name: product_db
      schema: product_schema
      username: product_service
      password: 'product_pass'

    review:
      name: review_db
      schema: review_schema
      username: review_service
      password: 'review_pass'

    user:
      name: user_db
      schema: user_schema
      username: user_service
      password: 'user_pass'
