spring:
  config:
    import: "optional:kubernetes:"
  application:
    name: review-service
  profiles:
    group:
      dev: "security,kafka,cache,feign,jpa,mongo"
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        include-profile-specific-sources: false
        enabled: true
        sources:
          - namespace: spring-market
            name: common-config-dev

          - namespace: spring-market
            name: review-service-dev

          - namespace: spring-market
            name: review-service-cache

          - namespace: spring-market
            name: review-service-kafka

          - namespace: spring-market
            name: review-service-security

          - namespace: spring-market
            name: review-service-feign

          - namespace: spring-market
            name: review-service-jpa

          - namespace: spring-market
            name: review-service-mongo
