apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: category-service
  name: category-service-cache
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |-
    spring:
      cache:
        enabled: true
      data:
        redis:
          host: redis.database.svc.cluster.local
          port: 6379