{{- $service := .Values.messaging.services.debezium }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium
  namespace: {{ .Values.namespace }}
  labels:
    app: debezium
spec:
  replicas: {{ $service.replicaCount }}
  selector:
    matchLabels:
      app: debezium
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
        - env:
            - name: BOOTSTRAP_SERVERS
              value: kafka-0.kafka-headless.{{ .Values.namespace }}.svc.cluster.local:9090,kafka-1.kafka-headless.{{ .Values.namespace }}.svc.cluster.local:9090,kafka-2.kafka-headless.{{ .Values.namespace }}.svc.cluster.local:9090
            - name: CONFIG_STORAGE_TOPIC
              value: kafka-connect-config
            - name: GROUP_ID
              value: "1"
            - name: KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: KEY_CONVERTER_SCHEMAS_ENABLE
              value: "false"
            - name: OFFSET_STORAGE_TOPIC
              value: kafka-connect-offset
            - name: REST_PORT
              value: {{ $service.targetPort }}
            - name: STATUS_STORAGE_TOPIC
              value: kafka-connect-status
            - name: VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: VALUE_CONVERTER_SCHEMAS_ENABLE
              value: "false"

          image: debezium/connect:2.7.3.Final
          livenessProbe:
            httpGet:
              port: {{ $service.targetPort }}
              path: /connectors
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          name: debezium
          ports:
            - containerPort: {{ $service.targetPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /debezium
              name: debezium-data

            - mountPath: /docker-entrypoint-init.d
              name: debezium-config

          resources:
            requests:
              memory: {{ $service.resources.requests.memory }}
              cpu: {{ $service.resources.requests.cpu }}
            limits:
              memory: {{ $service.resources.limits.memory }}
              cpu: {{ $service.resources.limits.cpu }}
      hostname: debezium
      restartPolicy: Always
      volumes:
        - name: debezium-data
          persistentVolumeClaim:
            claimName: debezium-data

        - name: debezium-config
          configMap:
            name: debezium-config

