apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debezium-data
  namespace: {{ .Values.namespace }}
  labels:
    app: debezium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.messaging.services.debezium.resources.requests.storage }}
