apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: payment-service
  name: payment-service
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |
    server:
      port: {{ index .Values.spring.services "payment-service" "port" }}
      shutdown: graceful

    springdoc:
      api-docs:
        path: /payment-service/v3/api-docs
      swagger-ui:
        path: /payment-service/swagger-ui.html

    stripe:
      secret:
        key: ${STRIPE_SECRET_KEY}