spring:
  config:
    import: "optional:kubernetes:"
  application:
    name: notification-service
  profiles:
    group:
      dev: "security,kafka"
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        enabled: true
        sources:
          - namespace: spring-market
            name: common-config-dev

          - namespace: spring-market
            name: notification-service-dev

          - namespace: spring-market
            name: notification-service-security

          - namespace: spring-market
            name: notification-service-kafka
