spring:
  config:
    import: "optional:kubernetes:"
  application:
    name: notification-service
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        enabled: true
        include-profile-specific-sources: false
        sources:
          - namespace: spring-market
            name: common-config

          - namespace: spring-market
            name: notification-service

          - namespace: spring-market
            name: notification-service-security

          - namespace: spring-market
            name: notification-service-kafka
