server:
  port: 8084
spring:
  application:
    name: CartService
  datasource:
    url: jdbc:postgresql://localhost:5432/cart_db
    username: admin
    password: $2a$12$WHDRyXGTErJoxwlXnU7tquYrgnSaPoh5D.iCmqnNk17Mdsii17CZO
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761