apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: cart-service
  name: cart-service
  namespace: spring-market
data:
  application.yaml: |-
    server:
      port: 8084
      shutdown: graceful

    springdoc:
      api-docs:
        path: /cart-service/v3/api-docs
      swagger-ui:
        path: /cart-service/swagger-ui.html