apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: saga-service
  name: saga-service-security
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |
    spring:
      security:
        enabled: true