apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: saga-service
  name: saga-service
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |
    server:
      port: {{ index .Values.spring.services "saga-service" "port" }}
      shutdown: graceful