apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-market
  name: payment-service
  labels:
    app: payment-service
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        version: v1

    spec:
      serviceAccountName: spring-services-sa
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -XX:ActiveProcessorCount=2 -XX:MaxRAMPercentage=70.0 -javaagent:/app/opentelemetry-javaagent.jar
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://grafana-tempo.observability.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_INSTRUMENTATION_SPRING_WEBMVC_EXCLUDED_PATHS
              value: /actuator/**
            - name: OTEL_LOGS_EXPORTER
              value: logging
            - name: OTEL_METRICS_EXPORTER
              value: prometheus
            - name: OTEL_SERVICE_NAME
              value: payment-service
            - name: OTEL_SERVICE_VERSION
              value: 1.0.0
            - name: OTEL_TRACES_EXPORTER
              value: otlp,logging
            - name: SPRING_PROFILES_ACTIVE
              value: security,kafka,cache,jpa,mongo
          envFrom:
            - configMapRef:
                name: env-local

          image: ghcr.io/cryptic901/springmarket/payment-service:develop-e2e2785
          imagePullPolicy: IfNotPresent
          name: payment-service
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
            - name: metrics
              containerPort: 9464
              protocol: TCP
          restartPolicy: Always

          livenessProbe:
            httpGet:
              port: 8088
              path: /actuator/health/liveness
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              port: 8088
              path: /actuator/health/readiness
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 3

          startupProbe:
            httpGet:
              port: 8088
              path: /actuator/health/liveness
            initialDelaySeconds: 20
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5

          resources:
            requests:
              memory: "650Mi"
              cpu: "450m"
            limits:
              memory: "1300Mi"
              cpu: "750m"
