apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: product-service
  name: product-service
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |-
    server:
      port: {{ index .Values.spring.services.productService.port }}
      shutdown: graceful

    springdoc:
      api-docs:
        path: /product-service/v3/api-docs
      swagger-ui:
        path: /product-service/swagger-ui.html